# Generated by Django 5.2.8 on 2026-03-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('group', models.CharField(max_length=50)),
                ('graduation_year', models.IntegerField()),
                ('status', models.CharField(choices=[('work', 'Трудоустроен'), ('study', 'Учится'), ('army', 'Армия'), ('unemployed', 'Безработный')], max_length=20)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
