# Generated by Django 5.2.8 on 2026-03-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
